### ISSUE TITLE
Install Issues with Soundflower make use of soundcast impossible

### ISSUE THREAD

**Issue by joelneubert** [andresgottlieb/soundcast#4]
https://github.com/RogueAmoeba/Soundflower/issues/33

I've tried numerous times to get this going. 

1. No support response to this issue posted in May
2. Soundflower is open source
3. Soundcast could implement this functionality without the additional dependency

Just a thought that it would be ideal to drop this dependency, and maybe the open source nature of Sounflower would allow some of that to happen. It truly appears that their is no or very little support for the Soundflower project anymore.

**Comment by joelneubert** [comment]
I'd be open for suggestions, I'm on El Cap, I've seen users with this same issue on Yoesmite, no resolution, and generally use another program. Is that a possibility?

**Comment by andresgottlieb** [comment]
Hi @joelneubert,

  Well, it's definitely possible to use another program. The only requisite is that the program must take the system's sound output and route it through a virtual system input. From then on, we just have to tell Soundcast to se that virtual input instead of Soundflower's.

  Do you know of an alternative to Soundflower able to do this?

**Comment by joelneubert** [comment]
I'm trying 'Audio Hijack' I'm not positive how that setup is working but it appears to work decently.

**Comment by andresgottlieb** [comment]
@joelneubert just writing to let you know that others using OS X El Capitan also reported issues and that there's a way to get this to work using a newer version of Soundflower. Just check out [this thread](https://github.com/andresgottlieb/soundcast/issues/5#issuecomment-145387697).
